# Generated by Django 4.0.1 on 2022-03-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_tmdb_id'),
        ('rating', '0002_alter_rating_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='tmdb_id',
            field=models.ForeignKey(db_column='tmdb_id', on_delete=django.db.models.deletion.CASCADE, to='movie.movie', to_field='tmdb_id'),
        ),
    ]
