# Generated by Django 4.0.1 on 2022-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_binary_directors_binary_languages'),
        ('rating', '0003_alter_rating_tmdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('movie', models.ManyToManyField(to='movie.Movie')),
            ],
        ),
    ]
