# Generated by Django 4.0.1 on 2022-03-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='timestamp',
            field=models.DateTimeField(default='1970-01-01'),
            preserve_default=False,
        ),
    ]
