# Generated by Django 4.0.1 on 2022-03-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_binary_directors_binary_languages'),
        ('rating', '0005_rating_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movie', models.ManyToManyField(to='movie.Movie')),
            ],
        ),
    ]
