# Generated by Django 4.0.1 on 2022-03-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
