# Generated by Django 4.0.1 on 2022-02-22 19:15

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('backdrop', models.ImageField(upload_to='backdrops')),
                ('budget', models.IntegerField()),
                ('genres', jsonfield.fields.JSONField()),
                ('keywords', jsonfield.fields.JSONField()),
                ('original_title', models.CharField(max_length=100)),
                ('overview', models.TextField(blank=True, max_length=1000, null=True)),
                ('popularity', models.FloatField()),
                ('poster', models.ImageField(upload_to='posters')),
                ('release_date', models.DateField()),
                ('revenue', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('tagline', models.TextField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(max_length=100)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
