# Generated by Django 4.0.1 on 2022-03-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
