# Generated by Django 4.0.1 on 2022-03-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(unique=True),
        ),
    ]
