# Generated by Django 4.0.1 on 2022-03-09 11:55

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=jsonfield.fields.JSONField(default='unknown'),
            preserve_default=False,
        ),
    ]
