# Generated by Django 4.0.1 on 2022-03-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_director_movie_original_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='production_companies',
        ),
        migrations.AddField(
            model_name='movie',
            name='production_company',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
